// ============================================================
// FILE: alignment_bill_add_edit_screen.dart
//
// PURPOSE:
// Add, edit and duplicate Simple Alignment Bills.
//
// IMPORTANT:
// - Alignment Billing does NOT use GST.
// - Customer is selected from the existing Customer module.
// - Customer search supports Name OR Customer Number.
// - If a customer does not exist, Create Customer can be used.
// - First bill number is entered manually.
// - Later bill numbers are generated automatically.
// ============================================================

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';

import '../models/alignment_bill.dart';
import '../models/customer.dart';
import '../repositories/alignment_bill_repository.dart';
import '../repositories/customer_repository.dart';
import 'add_edit_customer_screen.dart';

class AlignmentBillAddEditScreen extends StatefulWidget {
  final AlignmentBill? bill;
  final bool isDuplicate;

  const AlignmentBillAddEditScreen({
    super.key,
    this.bill,
    this.isDuplicate = false,
  });

  @override
  State<AlignmentBillAddEditScreen> createState() =>
      _AlignmentBillAddEditScreenState();
}

class _AlignmentBillAddEditScreenState
    extends State<AlignmentBillAddEditScreen> {
  // ------------------------------------------------------------
  // FORM
  // ------------------------------------------------------------

  final GlobalKey<FormState> _formKey =
  GlobalKey<FormState>();

  // ------------------------------------------------------------
  // REPOSITORIES
  // ------------------------------------------------------------

  final AlignmentBillRepository _billRepository =
  AlignmentBillRepository();

  final CustomerRepository _customerRepository =
  CustomerRepository();

  // ------------------------------------------------------------
  // CONTROLLERS
  // ------------------------------------------------------------

  final TextEditingController _billNumberController =
  TextEditingController();

  final TextEditingController _customerNameController =
  TextEditingController();

  final TextEditingController _customerNumberController =
  TextEditingController();

  final TextEditingController _addressController =
  TextEditingController();

  final TextEditingController _vehicleNumberController =
  TextEditingController();

  final TextEditingController _kmsController =
  TextEditingController();

  final TextEditingController _serviceController =
  TextEditingController(
    text: 'Wheel Alignment',
  );

  final TextEditingController _quantityController =
  TextEditingController(
    text: '1',
  );

  final TextEditingController _rateController =
  TextEditingController();

  final TextEditingController _remarksController =
  TextEditingController();

  // ------------------------------------------------------------
  // STATE
  // ------------------------------------------------------------

  Customer? _selectedCustomer;

  DateTime _selectedDate = DateTime.now();

  String _paymentMethod = 'Cash';

  bool _loading = true;

  bool _saving = false;

  bool _isBillAutoGenerated = false;

  // ------------------------------------------------------------
  // EDIT MODE
  // ------------------------------------------------------------

  bool get _isEdit =>
      widget.bill != null &&
          !widget.isDuplicate;

  // ------------------------------------------------------------
  // BILL NUMBER LOCK
  // ------------------------------------------------------------

  bool get _isBillNumberLocked =>
      _isEdit ||
          widget.isDuplicate ||
          _isBillAutoGenerated;

  // ============================================================
  // INITIALIZATION
  // ============================================================

  @override
  void initState() {
    super.initState();

    _initialize();
  }

  Future<void> _initialize() async {
    try {
      // --------------------------------------------------------
      // EDIT
      // --------------------------------------------------------

      if (widget.bill != null) {
        await _loadExistingBill(
          widget.bill!,
        );
      } else {
        // ------------------------------------------------------
        // NEW BILL
        // ------------------------------------------------------

        final String? nextBillNumber =
        await _billRepository
            .generateNextBillNumber();

        if (nextBillNumber == null) {
          // No previous bill exists.
          //
          // The user must enter the first bill number manually.
          _billNumberController.clear();

          _isBillAutoGenerated = false;
        } else {
          // A previous bill exists, so generate the next number.
          _billNumberController.text =
              nextBillNumber;

          _isBillAutoGenerated = true;
        }
      }

      // --------------------------------------------------------
      // DUPLICATE
      // --------------------------------------------------------

      if (widget.isDuplicate &&
          widget.bill != null) {
        final String? nextBillNumber =
        await _billRepository
            .generateNextBillNumber();

        if (nextBillNumber != null) {
          _billNumberController.text =
              nextBillNumber;

          _isBillAutoGenerated = true;
        }
      }
    } catch (error) {
      if (mounted) {
        _showError(
          'Unable to load Alignment Bill.\n$error',
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _loading = false;
        });
      }
    }
  }

  // ============================================================
  // LOAD EXISTING BILL
  // ============================================================

  Future<void> _loadExistingBill(
      AlignmentBill bill,
      ) async {
    _billNumberController.text =
        bill.billNumber;

    _customerNameController.text =
        bill.customerName;

    _customerNumberController.text =
        bill.customerNumber;

    _addressController.text =
        bill.address ?? '';

    _vehicleNumberController.text =
        bill.vehicleNumber;

    _kmsController.text =
        bill.kms.toString();

    _serviceController.text =
        bill.service;

    _quantityController.text =
        _formatNumber(bill.quantity);

    _rateController.text =
        _formatNumber(bill.rate);

    _remarksController.text =
        bill.remarks;

    _selectedDate = bill.date;

    _paymentMethod =
        bill.paymentMethod;

    // Load the actual customer record when the
    // bill contains a customer ID.
    if (bill.customerId != null) {
      _selectedCustomer =
      await _customerRepository
          .getCustomerById(
        bill.customerId!,
      );
    }
  }

  // ============================================================
  // CUSTOMER SELECTION
  // ============================================================

  Future<void> _selectCustomer() async {
    final Customer? customer =
    await showDialog<Customer>(
      context: context,
      builder: (BuildContext context) {
        return const _CustomerSearchDialog();
      },
    );

    if (!mounted || customer == null) {
      return;
    }

    _applyCustomer(customer);
  }

  // ============================================================
  // APPLY CUSTOMER
  // ============================================================

  void _applyCustomer(Customer customer) {
    setState(() {
      _selectedCustomer = customer;

      _customerNameController.text =
          customer.name;

      _customerNumberController.text =
          customer.phone;

      _addressController.text =
          customer.address ?? '';
    });
  }

  // ============================================================
  // CREATE CUSTOMER
  // ============================================================

  Future<void> _createCustomer() async {
    // Keep the IDs that existed before opening the
    // Customer creation screen.
    final List<Customer> before =
    await _customerRepository
        .getCustomers();

    final Set<int> oldIds = before
        .where(
          (Customer customer) =>
      customer.id != null,
    )
        .map(
          (Customer customer) =>
      customer.id!,
    )
        .toSet();

    if (!mounted) {
      return;
    }

    final dynamic result =
    await Navigator.of(context).push(
      MaterialPageRoute<dynamic>(
        builder: (BuildContext context) {
          return const AddEditCustomerScreen();
        },
      ),
    );

    if (!mounted || result != true) {
      return;
    }

    // Read customers again after the new customer
    // was created.
    final List<Customer> after =
    await _customerRepository
        .getCustomers();

    Customer? newCustomer;

    // Find the newly-created customer.
    for (final Customer customer in after) {
      if (customer.id != null &&
          !oldIds.contains(customer.id)) {
        newCustomer = customer;
        break;
      }
    }

    // Fallback in case the database implementation
    // returns the records in an unexpected order.
    newCustomer ??=
    after.isNotEmpty
        ? after.first
        : null;

    if (newCustomer != null) {
      _applyCustomer(newCustomer);
    }
  }

  // ============================================================
  // DATE PICKER
  // ============================================================

  Future<void> _pickDate() async {
    final DateTime? picked =
    await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime(2000),
      lastDate: DateTime(2100),
    );

    if (picked == null || !mounted) {
      return;
    }

    setState(() {
      _selectedDate = DateTime(
        picked.year,
        picked.month,
        picked.day,
      );
    });
  }

  // ============================================================
  // AMOUNT CALCULATION
  // ============================================================

  double get _quantity {
    return double.tryParse(
      _quantityController.text.trim(),
    ) ??
        0;
  }

  double get _rate {
    return double.tryParse(
      _rateController.text.trim(),
    ) ??
        0;
  }

  double get _amount {
    return _quantity * _rate;
  }

  // ============================================================
  // SAVE
  // ============================================================

  Future<void> _save() async {
    // Validate all form fields first.
    if (!_formKey.currentState!.validate()) {
      return;
    }

    // A customer must be selected.
    if (_selectedCustomer == null) {
      _showError(
        'Please select a customer.',
      );
      return;
    }

    // Customer ID must exist because the selected customer
    // comes from the Customer table.
    if (_selectedCustomer!.id == null) {
      _showError(
        'Selected customer has no valid ID.',
      );
      return;
    }

    final String billNumber =
    _billNumberController.text.trim();

    // Check duplicate bill number only for new bills.
    if (!_isEdit) {
      try {
        final bool exists =
        await _billRepository
            .billNumberExists(
          billNumber,
        );

        if (exists) {
          _showError(
            'Bill number already exists.',
          );
          return;
        }
      } catch (error) {
        _showError(
          'Unable to validate bill number.\n$error',
        );
        return;
      }
    }

    setState(() {
      _saving = true;
    });

    try {
      final DateTime now =
      DateTime.now();

      final AlignmentBill alignmentBill =
      AlignmentBill(
        // Keep the existing database ID during editing.
        id: _isEdit
            ? widget.bill!.id
            : null,

        billNumber: billNumber,

        date: _selectedDate,

        customerId:
        _selectedCustomer!.id,

        customerName:
        _customerNameController
            .text
            .trim(),

        customerNumber:
        _customerNumberController
            .text
            .trim(),

        address:
        _addressController.text
            .trim()
            .isEmpty
            ? null
            : _addressController.text
            .trim(),

        vehicleNumber:
        _vehicleNumberController
            .text
            .trim(),

        kms: int.tryParse(
          _kmsController.text.trim(),
        ) ??
            0,

        service:
        _serviceController.text
            .trim(),

        quantity: _roundNumber(
          _quantity,
        ),

        rate: _roundMoney(
          _rate,
        ),

        amount: _roundMoney(
          _amount,
        ),

        paymentMethod:
        _paymentMethod,

        remarks:
        _remarksController.text
            .trim(),

        // Preserve original creation date during editing.
        createdAt: _isEdit
            ? widget.bill!.createdAt
            : now,

        updatedAt: now,
      );

      if (_isEdit) {
        // Update existing record.
        await _billRepository
            .updateBill(
          alignmentBill,
        );
      } else {
        // Insert new record.
        await _billRepository
            .addBill(
          alignmentBill,
        );
      }

      if (!mounted) {
        return;
      }

      ScaffoldMessenger.of(context)
          .showSnackBar(
        SnackBar(
          content: Text(
            _isEdit
                ? 'Alignment Bill updated successfully.'
                : 'Alignment Bill saved successfully.',
          ),
        ),
      );

      // Tell the main Alignment Billing screen
      // that the bill was saved.
      Navigator.of(context).pop(true);
    } catch (error) {
      if (mounted) {
        _showError(
          'Unable to save Alignment Bill.\n$error',
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _saving = false;
        });
      }
    }
  }

  // ============================================================
  // DISPOSE
  // ============================================================

  @override
  void dispose() {
    _billNumberController.dispose();
    _customerNameController.dispose();
    _customerNumberController.dispose();
    _addressController.dispose();
    _vehicleNumberController.dispose();
    _kmsController.dispose();
    _serviceController.dispose();
    _quantityController.dispose();
    _rateController.dispose();
    _remarksController.dispose();

    super.dispose();
  }

  // ============================================================
  // BUILD
  // ============================================================

  @override
  Widget build(BuildContext context) {
    final String title = _isEdit
        ? 'Edit Alignment Bill'
        : widget.isDuplicate
        ? 'Duplicate Alignment Bill'
        : 'New Alignment Bill';

    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),

      body: _loading
          ? const Center(
        child:
        CircularProgressIndicator(),
      )
          : Form(
        key: _formKey,
        child: ListView(
          padding:
          const EdgeInsets.fromLTRB(
            16,
            16,
            16,
            100,
          ),
          children: <Widget>[
            _buildBillSection(),

            const SizedBox(height: 16),

            _buildCustomerSection(),

            const SizedBox(height: 16),

            _buildVehicleSection(),

            const SizedBox(height: 16),

            _buildServiceSection(),

            const SizedBox(height: 16),

            _buildPaymentSection(),

            const SizedBox(height: 16),

            _buildRemarksSection(),

            const SizedBox(height: 24),

            _buildSaveButton(),
          ],
        ),
      ),
    );
  }

  // ============================================================
  // BILL SECTION
  // ============================================================

  Widget _buildBillSection() {
    return _sectionCard(
      title: 'Bill Details',
      icon: Icons.receipt_long_outlined,
      children: <Widget>[
        TextFormField(
          controller:
          _billNumberController,
          readOnly: _isBillNumberLocked,
          decoration: InputDecoration(
            labelText: 'Bill Number',
            hintText:
            _isBillNumberLocked
                ? null
                : 'Example: AL001',
            prefixIcon:
            const Icon(
              Icons.numbers,
            ),
            suffixIcon:
            _isBillNumberLocked
                ? const Icon(
              Icons.lock_outline,
            )
                : null,
            border:
            const OutlineInputBorder(),
          ),
          validator: (String? value) {
            if (value == null ||
                value.trim().isEmpty) {
              return 'Enter bill number';
            }

            return null;
          },
        ),

        const SizedBox(height: 12),

        InkWell(
          onTap: _pickDate,
          borderRadius:
          BorderRadius.circular(4),
          child: InputDecorator(
            decoration:
            const InputDecoration(
              labelText: 'Bill Date',
              prefixIcon: Icon(
                Icons.calendar_today_outlined,
              ),
              border:
              OutlineInputBorder(),
            ),
            child: Text(
              DateFormat(
                'dd/MM/yyyy',
              ).format(
                _selectedDate,
              ),
            ),
          ),
        ),
      ],
    );
  }

  // ============================================================
  // CUSTOMER SECTION
  // ============================================================

  Widget _buildCustomerSection() {
    return _sectionCard(
      title: 'Customer',
      icon: Icons.person_outline,
      children: <Widget>[
        Row(
          children: <Widget>[
            Expanded(
              child:
              OutlinedButton.icon(
                onPressed:
                _selectCustomer,
                icon: const Icon(
                  Icons.search,
                ),
                label: const Text(
                  'Search Customer',
                ),
              ),
            ),

            const SizedBox(width: 8),

            OutlinedButton.icon(
              onPressed:
              _createCustomer,
              icon: const Icon(
                Icons.person_add_alt_1,
              ),
              label: const Text(
                'Create',
              ),
            ),
          ],
        ),

        const SizedBox(height: 12),

        TextFormField(
          controller:
          _customerNameController,
          readOnly: true,
          decoration:
          const InputDecoration(
            labelText: 'Customer Name',
            prefixIcon: Icon(
              Icons.person_outline,
            ),
            border:
            OutlineInputBorder(),
          ),
          validator: (String? value) {
            if (value == null ||
                value.trim().isEmpty) {
              return 'Select a customer';
            }

            return null;
          },
        ),

        const SizedBox(height: 12),

        TextFormField(
          controller:
          _customerNumberController,
          readOnly: true,
          decoration:
          const InputDecoration(
            labelText: 'Customer Number',
            prefixIcon: Icon(
              Icons.phone_outlined,
            ),
            border:
            OutlineInputBorder(),
          ),
        ),

        const SizedBox(height: 12),

        TextFormField(
          controller:
          _addressController,
          readOnly: true,
          maxLines: 2,
          decoration:
          const InputDecoration(
            labelText: 'Address',
            prefixIcon: Icon(
              Icons.location_on_outlined,
            ),
            border:
            OutlineInputBorder(),
          ),
        ),
      ],
    );
  }

  // ============================================================
  // VEHICLE SECTION
  // ============================================================

  Widget _buildVehicleSection() {
    return _sectionCard(
      title: 'Vehicle',
      icon:
      Icons.directions_car_outlined,
      children: <Widget>[
        TextFormField(
          controller:
          _vehicleNumberController,
          textCapitalization:
          TextCapitalization.characters,
          inputFormatters:
          <TextInputFormatter>[
            FilteringTextInputFormatter.allow(
              RegExp(r'[A-Za-z0-9 -]'),
            ),
          ],
          decoration:
          const InputDecoration(
            labelText: 'Vehicle Number',
            hintText:
            'Example: KA01AB1234',
            prefixIcon: Icon(
              Icons.directions_car_outlined,
            ),
            border:
            OutlineInputBorder(),
          ),
          validator: (String? value) {
            if (value == null ||
                value.trim().isEmpty) {
              return 'Enter vehicle number';
            }

            return null;
          },
        ),

        const SizedBox(height: 12),

        TextFormField(
          controller: _kmsController,
          keyboardType:
          TextInputType.number,
          inputFormatters:
          <TextInputFormatter>[
            FilteringTextInputFormatter
                .digitsOnly,
          ],
          decoration:
          const InputDecoration(
            labelText: 'KMS',
            hintText:
            'Example: 45280',
            prefixIcon: Icon(
              Icons.speed_outlined,
            ),
            border:
            OutlineInputBorder(),
          ),
          validator: (String? value) {
            final String text =
                value?.trim() ?? '';

            if (text.isEmpty) {
              return 'Enter KMS';
            }

            final int? kms =
            int.tryParse(text);

            if (kms == null) {
              return 'Enter a valid KMS';
            }

            if (kms < 0) {
              return 'KMS cannot be negative';
            }

            return null;
          },
        ),
      ],
    );
  }

  // ============================================================
  // SERVICE SECTION
  // ============================================================

  Widget _buildServiceSection() {
    return _sectionCard(
      title: 'Alignment Service',
      icon:
      Icons.car_repair_outlined,
      children: <Widget>[
        TextFormField(
          controller:
          _serviceController,
          decoration:
          const InputDecoration(
            labelText: 'Service',
            hintText:
            'Example: Wheel Alignment',
            prefixIcon: Icon(
              Icons.car_repair_outlined,
            ),
            border:
            OutlineInputBorder(),
          ),
          validator: (String? value) {
            if (value == null ||
                value.trim().isEmpty) {
              return 'Enter service';
            }

            return null;
          },
        ),

        const SizedBox(height: 12),

        Row(
          crossAxisAlignment:
          CrossAxisAlignment.start,
          children: <Widget>[
            Expanded(
              child: TextFormField(
                controller:
                _quantityController,
                keyboardType:
                const TextInputType.numberWithOptions(
                  decimal: true,
                ),
                inputFormatters:
                <TextInputFormatter>[
                  FilteringTextInputFormatter.allow(
                    RegExp(
                      r'^\d*\.?\d{0,2}',
                    ),
                  ),
                ],
                onChanged: (_) {
                  setState(() {});
                },
                decoration:
                const InputDecoration(
                  labelText: 'Quantity',
                  prefixIcon: Icon(
                    Icons.format_list_numbered,
                  ),
                  border:
                  OutlineInputBorder(),
                ),
                validator:
                    (String? value) {
                  final double quantity =
                      double.tryParse(
                        value?.trim() ??
                            '',
                      ) ??
                          0;

                  if (quantity <= 0) {
                    return 'Required';
                  }

                  return null;
                },
              ),
            ),

            const SizedBox(width: 10),

            Expanded(
              child: TextFormField(
                controller:
                _rateController,
                keyboardType:
                const TextInputType.numberWithOptions(
                  decimal: true,
                ),
                inputFormatters:
                <TextInputFormatter>[
                  FilteringTextInputFormatter.allow(
                    RegExp(
                      r'^\d*\.?\d{0,2}',
                    ),
                  ),
                ],
                onChanged: (_) {
                  setState(() {});
                },
                decoration:
                const InputDecoration(
                  labelText: 'Rate',
                  prefixText: '₹ ',
                  prefixIcon: Icon(
                    Icons.currency_rupee,
                  ),
                  border:
                  OutlineInputBorder(),
                ),
                validator:
                    (String? value) {
                  final double rate =
                      double.tryParse(
                        value?.trim() ??
                            '',
                      ) ??
                          -1;

                  if (rate < 0) {
                    return 'Required';
                  }

                  return null;
                },
              ),
            ),
          ],
        ),

        const SizedBox(height: 12),

        Container(
          width: double.infinity,
          padding:
          const EdgeInsets.all(14),
          decoration:
          BoxDecoration(
            color:
            Colors.orange.shade50,
            borderRadius:
            BorderRadius.circular(
              10,
            ),
          ),
          child: Row(
            mainAxisAlignment:
            MainAxisAlignment
                .spaceBetween,
            children: <Widget>[
              const Text(
                'Total Amount',
                style: TextStyle(
                  fontWeight:
                  FontWeight.bold,
                ),
              ),
              Text(
                '₹${_amount.toStringAsFixed(2)}',
                style:
                const TextStyle(
                  fontSize: 18,
                  fontWeight:
                  FontWeight.bold,
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  // ============================================================
  // PAYMENT SECTION
  // ============================================================

  Widget _buildPaymentSection() {
    return _sectionCard(
      title: 'Payment',
      icon:
      Icons.payments_outlined,
      children: <Widget>[
        DropdownButtonFormField<String>(
          initialValue:
          _paymentMethod,
          decoration:
          const InputDecoration(
            labelText:
            'Payment Method',
            prefixIcon: Icon(
              Icons.payment_outlined,
            ),
            border:
            OutlineInputBorder(),
          ),
          items:
          const <DropdownMenuItem<
              String>>[
            DropdownMenuItem(
              value: 'Cash',
              child: Text('Cash'),
            ),
            DropdownMenuItem(
              value: 'G Pay',
              child: Text('G Pay'),
            ),
          ],
          onChanged:
              (String? value) {
            if (value == null) {
              return;
            }

            setState(() {
              _paymentMethod =
                  value;
            });
          },
        ),
      ],
    );
  }

  // ============================================================
  // REMARKS SECTION
  // ============================================================

  Widget _buildRemarksSection() {
    return _sectionCard(
      title: 'Remarks',
      icon: Icons.notes_outlined,
      children: <Widget>[
        TextFormField(
          controller:
          _remarksController,
          maxLines: 3,
          decoration:
          const InputDecoration(
            hintText:
            'Optional remarks',
            border:
            OutlineInputBorder(),
          ),
        ),
      ],
    );
  }

  // ============================================================
  // SAVE BUTTON
  // ============================================================

  Widget _buildSaveButton() {
    return SizedBox(
      height: 52,
      child: FilledButton.icon(
        onPressed:
        _saving ? null : _save,
        icon: _saving
            ? const SizedBox(
          width: 20,
          height: 20,
          child:
          CircularProgressIndicator(
            strokeWidth: 2,
          ),
        )
            : const Icon(
          Icons.save_outlined,
        ),
        label: Text(
          _saving
              ? 'Saving...'
              : _isEdit
              ? 'Update Alignment Bill'
              : 'Save Alignment Bill',
        ),
      ),
    );
  }

  // ============================================================
  // SECTION CARD
  // ============================================================

  Widget _sectionCard({
    required String title,
    required IconData icon,
    required List<Widget> children,
  }) {
    return Card(
      child: Padding(
        padding:
        const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment:
          CrossAxisAlignment.start,
          children: <Widget>[
            Row(
              children: <Widget>[
                Icon(icon),
                const SizedBox(width: 10),
                Text(
                  title,
                  style:
                  Theme.of(context)
                      .textTheme
                      .titleMedium
                      ?.copyWith(
                    fontWeight:
                    FontWeight.bold,
                  ),
                ),
              ],
            ),

            const SizedBox(height: 16),

            ...children,
          ],
        ),
      ),
    );
  }

  // ============================================================
  // NUMBER HELPERS
  // ============================================================

  double _roundMoney(double value) {
    return double.parse(
      value.toStringAsFixed(2),
    );
  }

  double _roundNumber(double value) {
    return double.parse(
      value.toStringAsFixed(2),
    );
  }

  String _formatNumber(double value) {
    if (value ==
        value.roundToDouble()) {
      return value.toInt().toString();
    }

    return value.toString();
  }

  // ============================================================
  // ERROR MESSAGE
  // ============================================================

  void _showError(String message) {
    ScaffoldMessenger.of(context)
        .showSnackBar(
      SnackBar(
        content: Text(message),
        behavior:
        SnackBarBehavior.floating,
      ),
    );
  }
}

// ============================================================
// CUSTOMER SEARCH DIALOG
// ============================================================
//
// Reuses the same customer-selection behavior already used
// by the Tyre Billing workflow.
//
// Search:
// - Customer Name
// - Customer Number
// ============================================================

class _CustomerSearchDialog
    extends StatefulWidget {
  const _CustomerSearchDialog();

  @override
  State<_CustomerSearchDialog> createState() =>
      _CustomerSearchDialogState();
}

class _CustomerSearchDialogState
    extends State<_CustomerSearchDialog> {
  // ------------------------------------------------------------
  // CUSTOMER REPOSITORY
  // ------------------------------------------------------------

  final CustomerRepository _repository =
  CustomerRepository();

  // ------------------------------------------------------------
  // SEARCH CONTROLLER
  // ------------------------------------------------------------

  final TextEditingController
  _searchController =
  TextEditingController();

  // ------------------------------------------------------------
  // STATE
  // ------------------------------------------------------------

  List<Customer> _customers =
  <Customer>[];

  bool _loading = true;

  // ============================================================
  // INITIALIZATION
  // ============================================================

  @override
  void initState() {
    super.initState();

    _loadCustomers();

    _searchController
        .addListener(_search);
  }

  // ============================================================
  // LOAD CUSTOMERS
  // ============================================================

  Future<void> _loadCustomers() async {
    final List<Customer> customers =
    await _repository
        .getCustomers();

    if (!mounted) {
      return;
    }

    setState(() {
      _customers = customers;
      _loading = false;
    });
  }

  // ============================================================
  // SEARCH CUSTOMERS
  // ============================================================

  Future<void> _search() async {
    final String query =
    _searchController.text.trim();

    final List<Customer> customers =
    await _repository
        .searchCustomers(query);

    if (!mounted) {
      return;
    }

    setState(() {
      _customers = customers;
    });
  }

  // ============================================================
  // DISPOSE
  // ============================================================

  @override
  void dispose() {
    _searchController
      ..removeListener(_search)
      ..dispose();

    super.dispose();
  }

  // ============================================================
  // BUILD
  // ============================================================

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text(
        'Select Customer',
      ),

      content: SizedBox(
        width: 500,
        height: 500,
        child: Column(
          children: <Widget>[
            // --------------------------------------------------
            // SEARCH FIELD
            // --------------------------------------------------

            TextField(
              controller:
              _searchController,
              autofocus: true,
              decoration:
              const InputDecoration(
                hintText:
                'Search name or customer number',
                prefixIcon:
                Icon(Icons.search),
                border:
                OutlineInputBorder(),
              ),
            ),

            const SizedBox(height: 12),

            // --------------------------------------------------
            // CUSTOMER LIST
            // --------------------------------------------------

            Expanded(
              child: _loading
                  ? const Center(
                child:
                CircularProgressIndicator(),
              )
                  : _customers.isEmpty
                  ? const Center(
                child: Text(
                  'Customer Not Found',
                ),
              )
                  : ListView.separated(
                itemCount:
                _customers.length,
                separatorBuilder:
                    (_, _) =>
                const Divider(
                  height: 1,
                ),
                itemBuilder:
                    (
                    BuildContext context,
                    int index,
                    ) {
                  final Customer
                  customer =
                  _customers[
                  index];

                  return ListTile(
                    leading:
                    const CircleAvatar(
                      child: Icon(
                        Icons
                            .person_outline,
                      ),
                    ),
                    title: Text(
                      customer.name,
                    ),
                    subtitle: Text(
                      customer.phone,
                    ),
                    onTap: () {
                      Navigator.of(
                        context,
                      ).pop(
                        customer,
                      );
                    },
                  );
                },
              ),
            ),
          ],
        ),
      ),

      actions: <Widget>[
        TextButton(
          onPressed: () {
            Navigator.of(context)
                .pop();
          },
          child:
          const Text('Cancel'),
        ),
      ],
    );
  }
}